apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-only
  namespace: monitoring
spec:
  ipAllowList:
    sourceRange:
      - 192.168.0.0/24
      - 127.0.0.1/32
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.kimsijun.com`)
      kind: Rule
      middlewares:
        - name: internal-only
      services:
        - name: monitoring-grafana
          port: 80
  tls:
    certResolver: letsencrypt
