apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: naver-news
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/sijunkim/naver-news-spring
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^master-
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sijunkim/infra.git
    targetRevision: master
    path: k8s/apps/naver-news
  destination:
    server: https://kubernetes.default.svc
    namespace: prodesk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
