apiVersion: v1
kind: Service
metadata:
  name: friend-external
  namespace: prodesk
spec:
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: friend-external
  namespace: prodesk
subsets:
  - addresses:
      - ip: 192.168.0.46
    ports:
      - port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: friend
  namespace: prodesk
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`friend.kimsijun.com`)
      kind: Rule
      services:
        - name: friend-external
          port: 3000
  tls:
    certResolver: letsencrypt
