apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: prodesk
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: prodesk
subsets:
  - addresses:
      - ip: 192.168.0.46
    ports:
      - port: 3306
