apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: prodesk
spec:
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: prodesk
subsets:
  - addresses:
      - ip: 192.168.0.46
    ports:
      - port: 6379
